# 02 · LoRA fine-tune — Qwen3-ASR-1.7B on Vietnamese

Fine-tunes `Qwen/Qwen3-ASR-1.7B-hf` with a **PEFT LoRA** adapter on a ~34 h
**multi-source Vietnamese mixture** (viVoice + VIVOS + Common Voice 17 `vi` +
VLSP 2020), validates on the mixture's `val`, and reports **before/after WER**
on the viVoice `test` split used by `01_eval_baseline.ipynb` (section 7) plus
the external benchmark suite (section 9).

> Sections 7 and 9 measure different things: viVoice `test` is speaker-disjoint
> and **unseen**, while the section 9 benchmarks are **in-domain** after this
> fine-tune. See `mixture.py` for how the eval rows are kept clean.

**16 GB VRAM budget:** batch size 1 · gradient accumulation 16 · gradient
checkpointing · bf16 · `adamw_torch_fused`. LoRA is attached to the **language
model decoder** — attention *and* MLP (audio encoder stays frozen).

**Baked-in facts from setup:**
- Audio passed to the processor as a numpy array (FFmpeg 4 file-decode is buggy here).
- Audio feature keys: `input_features`, `input_features_mask`.
- Requires `transformers>=5.14`.

## What changed since run 1

Run 1 was a null result: held-out viVoice WER 5.958% → 5.938%, a difference of
2 word errors in 10,155 (bootstrap 95% CI [-0.42%, +0.37%]). It also *lost*
4.5 points on VIVOS, 7.19% → 11.64%.

Root cause was in the data, not the optimizer — training was healthy throughout
(val loss 0.363 → 0.341 → 0.334, monotone). VIVOS ships ALL-CAPS transcripts and
was 59% of the mixture, so the model learned to condition casing on acoustic
domain and emitted uppercase for all 760 VIVOS test clips. Uppercase Vietnamese
has no whole-word tokens in the Qwen vocabulary, so generation dropped to roughly
character granularity in a token space with almost no language-model prior —
turning a cosmetic mismatch into phonetic errors ("trót" → "TÓT"). Fixed in
`mixture.py::normalize_train_text`; the cache is version-stamped so `data/vi_mix/`
rebuilds rather than being reused.

Three changes for run 2:
1. **Transcript casing normalized on ingest** — the actual bug.
2. **LoRA extended to the decoder MLP** — 6.4M → 17.4M trainable params (0.31% → 0.85%).
3. **LR 2e-4 → 1e-4** to match the larger adapted surface.

Only change 1 addresses a known defect; 2 and 3 are a bet that the null result
on viVoice was partly capacity. If run 2 fixes VIVOS but viVoice `test` still
does not move, the honest read is that 34 h is not enough to improve a model
already at 5.96% WER — not that the recipe needs more tuning.

Run 1's numbers live in `results/`; rerunning overwrites them, so copy that
directory aside first if you want the before/after side by side.

Run top-to-bottom (Kernel → Restart & Run All).

In [2]:
import os, random, numpy as np, torch
from dotenv import load_dotenv
load_dotenv()
assert os.environ.get("HF_TOKEN"), "Set HF_TOKEN in .env (see .env.example)"

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("torch", torch.__version__, "| device:", DEVICE,
      "|", torch.cuda.get_device_name(0) if DEVICE == "cuda" else "")

torch 2.8.0+cu128 | device: cuda | NVIDIA GeForce RTX 5080

## 1 · Build / load the training mixture
Reuses the shared `data/vi_asr/` viVoice cache and builds `data/vi_mix/`
(viVoice + VIVOS + Common Voice + VLSP 2020). Cache-aware: the first run
streams ~5 GB and writes 16 kHz wavs; later runs are a no-op.

In [3]:
import data_prep, mixture

# viVoice cache (also feeds the mixture) — no-op if already built
data_prep.prepare_dataset(target_hours=8.0)

# Multi-source training mixture: viVoice + VIVOS + Common Voice 17 vi + VLSP 2020.
# Cache-aware; the first build streams ~5 GB and writes 16 kHz wavs (~1 h).
mixture.prepare_mixture()

mix = data_prep.load_splits("data/vi_mix")
train, val = mix["train"], mix["val"]

# Drop the handful of very long clips. data_prep caps viVoice segments, but the
# streamed sources are uncapped: VLSP ships four clips of 61-81 s, well past the
# ~57 s longest clip whose memory use has actually been measured (6.7 GB peak).
# They are 0.02% of the mixture and the only untested OOM path in a ~7 h run.
MAX_TRAIN_S = 60.0
_before = len(train)
train = train.filter(lambda r: r["duration"] <= MAX_TRAIN_S)
print(f"dropped {_before - len(train)} train clips > {MAX_TRAIN_S:.0f}s "
      f"({_before} -> {len(train)})")

# `test` stays the viVoice held-out split so the before/after against
# results/baseline_metrics.json remains apples-to-apples. It is the only test set
# here that is still speaker-disjoint AND unseen. The external benchmarks are
# evaluated separately in section 9.
test = data_prep.load_splits("data/vi_asr")["test"]

print({"train": len(train), "val": len(val), "test (viVoice)": len(test)})
print(mixture.summarize(list(train)).to_string(index=False))

[data_prep] cache hit at data/vi_asr; skipping build.
[mixture] cache at data/vi_mix is v0, need v2 — rebuilding (~1 h, re-streams the non-viVoice sources).
[mixture] vivoice: reused 1302 rows from data/vi_asr

vivos:train: 0clip [00:00, ?clip/s]

cmv_vi:train: 0clip [00:00, ?clip/s]

cmv_vi:validation: 0clip [00:00, ?clip/s]

vlsp2020_100h:train: 0clip [00:00, ?clip/s]

Resolving data files:   0%|          | 0/35 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/35 [00:00<?, ?it/s]

Saving the dataset (0/1 shards):   0%|          | 0/19885 [00:00<?, ? examples/s]

[mixture] train: 19885 rows -> data/vi_mix/train

Saving the dataset (0/1 shards):   0%|          | 0/1014 [00:00<?, ? examples/s]

[mixture] val: 1014 rows -> data/vi_mix/val

Saving the dataset (0/1 shards):   0%|          | 0/390 [00:00<?, ? examples/s]

[mixture] test: 390 rows -> data/vi_mix/test

Saving the dataset (0/1 shards):   0%|          | 0/276 [00:00<?, ? examples/s]

[mixture] heldout vlsp2020_100h: 276 rows -> data/vi_mix/heldout_vlsp2020_100h

[mixture] training composition:
       source     n  hours
       cmv_vi  2298  2.895
      vivoice   980  6.409
        vivos 11660 14.921
vlsp2020_100h  4947  9.849

Filter:   0%|          | 0/19885 [00:00<?, ? examples/s]

dropped 4 train clips > 60s (19885 -> 19881)
{'train': 19881, 'val': 1014, 'test (viVoice)': 114}
       source     n  hours
       cmv_vi  2298  2.895
      vivoice   980  6.409
        vivos 11660 14.921
vlsp2020_100h  4943  9.775

## 2 · Load the base model + processor

In [4]:
from transformers import AutoProcessor, AutoModelForMultimodalLM
MODEL_ID = "Qwen/Qwen3-ASR-1.7B-hf"
processor = AutoProcessor.from_pretrained(MODEL_ID)
model = AutoModelForMultimodalLM.from_pretrained(
    MODEL_ID, dtype=torch.bfloat16, attn_implementation="sdpa", device_map=DEVICE,
)
print("loaded", type(model).__name__, model.dtype, model.device)

Loading weights:   0%|          | 0/707 [00:00<?, ?it/s]

loaded Qwen3ASRForConditionalGeneration torch.bfloat16 cuda:0

## 3 · Attach the LoRA adapter (decoder attention + MLP)

`q/k/v_proj` exist in both the audio encoder and the text decoder, so we match
**only** the `model.language_model` projections with a regex — the audio encoder
stays frozen.

The MLP projections (`gate/up/down_proj`) are included alongside attention. Run 1
adapted attention only (6.4M params, 0.31%) and moved the held-out viVoice WER by
2 word errors in 10,155 — indistinguishable from noise. The decoder MLP is where a
transformer stores most of its lexical knowledge, which is what adapting to a new
language's vocabulary actually needs. Learning rate drops 2e-4 → 1e-4 to match the
larger adapted surface.

In [5]:
from peft import LoraConfig, get_peft_model

# Full-match regex over module names -> only the 28 decoder layers, never the
# audio encoder. 4 attention + 3 MLP projections per layer = 196 total.
TARGET_RE = (r"model\.language_model\.layers\.\d+\."
             r"(self_attn\.(q_proj|k_proj|v_proj|o_proj)"
             r"|mlp\.(gate_proj|up_proj|down_proj))")

model.config.use_cache = False
model.gradient_checkpointing_enable()
model.enable_input_require_grads()   # required for grad checkpointing + PEFT

lora = LoraConfig(
    r=16, lora_alpha=32, lora_dropout=0.05, bias="none",
    task_type="CAUSAL_LM", target_modules=TARGET_RE,
)
model = get_peft_model(model, lora)
model.print_trainable_parameters()

adapted = [n for n, _ in model.named_modules() if n.endswith("lora_A.default")]
assert len(adapted) == 28 * 7, f"expected 196 LoRA-adapted projections, got {len(adapted)}"
# The audio encoder has q/k/v_proj and fc1/fc2 of its own, so a regex that
# widened by accident would silently unfreeze it — and the encoder is exactly
# what this run means to hold fixed.
assert not [n for n in adapted if ".language_model." not in n], \
    "LoRA leaked outside model.language_model — audio encoder must stay frozen"
print("LoRA-adapted projections:", len(adapted))

trainable params: 17,432,576 || all params: 2,055,485,056 || trainable%: 0.8481
LoRA-adapted projections: 196

## 4 · Data collator (on-the-fly)

For each raw example we build the ASR request (audio + prompt), then append the
target transcription tokens + EOS as **labels**, masking the prompt with `-100`.
Features are computed on the fly (not serialized to disk) since the dataset is small.

In [6]:
EOS_ID = processor.tokenizer.eos_token_id
PAD_ID = processor.tokenizer.pad_token_id

def collate(features):
    ids_list, lbl_list, feats, feat_masks = [], [], [], []
    for ex in features:
        arr, _ = data_prep.read_audio(ex["audio_path"])   # 16 kHz mono
        req = processor.apply_transcription_request(audio=arr, language="Vietnamese")
        p_ids = req["input_ids"][0]
        tgt = processor.tokenizer(ex["text"], add_special_tokens=False,
                                  return_tensors="pt")["input_ids"][0]
        tgt = torch.cat([tgt, torch.tensor([EOS_ID], dtype=tgt.dtype)])
        ids = torch.cat([p_ids, tgt])
        lbl = torch.cat([torch.full((len(p_ids),), -100, dtype=torch.long), tgt])
        ids_list.append(ids); lbl_list.append(lbl)
        feats.append(req["input_features"][0])
        feat_masks.append(req["input_features_mask"][0])

    maxlen = max(len(x) for x in ids_list)
    def pad1(x, val):
        return torch.cat([x, torch.full((maxlen - len(x),), val, dtype=x.dtype)])
    input_ids = torch.stack([pad1(x, PAD_ID) for x in ids_list])
    labels = torch.stack([pad1(x, -100) for x in lbl_list])
    attn = torch.stack([
        torch.cat([torch.ones(len(x), dtype=torch.long),
                   torch.zeros(maxlen - len(x), dtype=torch.long)]) for x in ids_list])

    maxT = max(f.shape[-1] for f in feats)
    input_features = torch.stack(
        [torch.cat([f, torch.zeros(f.shape[0], maxT - f.shape[-1], dtype=f.dtype)], dim=-1)
         for f in feats])
    input_features_mask = torch.stack(
        [torch.cat([m, torch.zeros(maxT - len(m), dtype=m.dtype)]) for m in feat_masks])

    return {"input_ids": input_ids, "attention_mask": attn, "labels": labels,
            "input_features": input_features, "input_features_mask": input_features_mask}

# sanity check on 2 examples
_b = collate([train[0], train[1]])
print({k: tuple(v.shape) for k, v in _b.items()})

{'input_ids': (2, 245), 'attention_mask': (2, 245), 'labels': (2, 245), 'input_features': (2, 128, 1300), 'input_features_mask': (2, 1300)}

## 5 · Training configuration

In [7]:
from transformers import Trainer, TrainerCallback, TrainingArguments

# ~19.9k samples / 16 accumulation = ~1243 optimizer steps per epoch, so one epoch
# is ~1.2k weight updates, not 1. Evaluating every 400 steps samples the
# validation curve 3 times -- enough to tell "still improving" from "overfitting",
# and to give load_best_model_at_end real candidates to choose from.
EVAL_EVERY = 400
LOG_EVERY = 5


class LossPrinter(TrainerCallback):
    """Print train and validation loss on their own lines.

    Needed because transformers' notebook progress table only writes a
    training-loss row when ``eval_strategy == "no"`` (see on_log in
    transformers/utils/notebook.py). With eval enabled the table is written
    only at eval time, so without this the first loss shown is at step 400.
    """

    def on_log(self, args, state, control, logs=None, **kwargs):
        if not logs:
            return
        step = f"{state.global_step:5d}/{state.max_steps}"
        if "loss" in logs:          # training log, every logging_steps
            print(f"[train] {step}  loss {logs['loss']:.4f}"
                  f"  lr {logs.get('learning_rate', float('nan')):.2e}", flush=True)
        if "eval_loss" in logs:     # evaluation log, every eval_steps
            print(f"[ val ] {step}  loss {logs['eval_loss']:.4f}"
                  f"  ({logs.get('eval_runtime', 0):.0f}s)", flush=True)


args = TrainingArguments(
    output_dir="checkpoints/vi_lora",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=16,
    # gradient_accumulation_steps=32,
    num_train_epochs=1,
    # 2e-4 was tuned for attention-only (6.4M params). Section 3 now adapts the
    # MLP too (17.4M, 2.7x the trainable surface), so halve it: the same step
    # size over more directions moves the decoder's lexical weights further
    # than intended, and those weights are what hold the language-model prior.
    learning_rate=1e-4,
    warmup_ratio=0.03,
    lr_scheduler_type="cosine",
    bf16=True,
    gradient_checkpointing=True,
    optim="adamw_torch_fused",
    logging_steps=LOG_EVERY,
    eval_strategy="steps",
    eval_steps=EVAL_EVERY,
    save_strategy="steps",
    save_steps=EVAL_EVERY,          # must equal eval_steps for load_best_model_at_end
    # Make the val split actually do its job: keep the checkpoint that validated
    # best rather than whichever ran last.
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    save_total_limit=2,             # best + latest; 1 can delete the best
    per_device_eval_batch_size=1,   # 16 GB: long clips OOM at the default 8
    report_to="none",
    seed=SEED,
    remove_unused_columns=False,   # our collator consumes the raw columns
    dataloader_num_workers=2,
)
trainer = Trainer(model=model, args=args, train_dataset=train,
                  eval_dataset=val, data_collator=collate,
                  callbacks=[LossPrinter()])

# ceil, matching how Trainer counts: the trailing partial accumulation group
# still fires an optimizer step.
steps_per_epoch = -(-len(train) // args.gradient_accumulation_steps)
total_steps = int(steps_per_epoch * args.num_train_epochs)
print(f"steps/epoch {steps_per_epoch}  total updates {total_steps}  "
      f"train-loss lines {total_steps // LOG_EVERY}  evals {total_steps // EVAL_EVERY}")

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

steps/epoch 1243  total updates 1243  train-loss lines 248  evals 3

## 6 · Train
Watch VRAM stay < 16 GB. Measured peak on this box was 6.7 GB with clips up to
~57 s, and cell 3 now drops anything over 60 s, so there is real headroom.
If you do OOM, raise `gradient_accumulation_steps` or lower `MAX_TRAIN_S` in
cell 3 — no rebuild needed, it filters the cached mixture in place.

Validation runs every `EVAL_EVERY` (400) steps. Watch `eval_loss`: if it is
still falling at the end the run is undertrained and a third epoch is
justified; if it turns upward, `load_best_model_at_end` will hand back the
best checkpoint rather than the last one, so the final adapter may not be the
one trained longest.

In [8]:
trainer.train()
trainer.save_model("checkpoints/vi_lora")   # saves the LoRA adapter
print("peak VRAM GB:", round(torch.cuda.max_memory_allocated() / 1e9, 2))
print("adapter saved -> checkpoints/vi_lora")

[transformers] `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

[train]     5/1243  loss 2.0951  lr 1.05e-05
[train]    10/1243  loss 1.6015  lr 2.37e-05
[train]    15/1243  loss 1.0258  lr 3.68e-05
[train]    20/1243  loss 0.3852  lr 5.00e-05
[train]    25/1243  loss 0.3972  lr 6.32e-05
[train]    30/1243  loss 0.3031  lr 7.63e-05
[train]    35/1243  loss 0.2603  lr 8.95e-05
[train]    40/1243  loss 0.3495  lr 1.00e-04
[train]    45/1243  loss 0.2033  lr 1.00e-04
[train]    50/1243  loss 0.3411  lr 1.00e-04
[train]    55/1243  loss 0.2739  lr 1.00e-04
[train]    60/1243  loss 0.3363  lr 9.99e-05
[train]    65/1243  loss 0.2740  lr 9.99e-05
[train]    70/1243  loss 0.2392  lr 9.98e-05
[train]    75/1243  loss 0.3628  lr 9.98e-05
[train]    80/1243  loss 0.2587  lr 9.97e-05
[train]    85/1243  loss 0.3561  lr 9.96e-05
[train]    90/1243  loss 0.2400  lr 9.96e-05
[train]    95/1243  loss 0.2551  lr 9.95e-05
[train]   100/1243  loss 0.2916  lr 9.94e-05
[train]   105/1243  loss 0.1901  lr 9.93e-05
[train]   110/1243  loss 0.3080  lr 9.91e-05
[train]   115/1243  loss 0.3201  lr 9.90e-05
[train]   120/1243  loss 0.1761  lr 9.89e-05
[train]   125/1243  loss 0.2703  lr 9.87e-05
[train]   130/1243  loss 0.2850  lr 9.86e-05
[train]   135/1243  loss 0.2257  lr 9.84e-05
[train]   140/1243  loss 0.3973  lr 9.83e-05
[train]   145/1243  loss 0.3560  lr 9.81e-05
[train]   150/1243  loss 0.3062  lr 9.79e-05
[train]   155/1243  loss 0.2495  lr 9.77e-05
[train]   160/1243  loss 0.2584  lr 9.75e-05
[train]   165/1243  loss 0.2342  lr 9.73e-05
[train]   170/1243  loss 0.2381  lr 9.71e-05
[train]   175/1243  loss 0.2578  lr 9.69e-05
[train]   180/1243  loss 0.1943  lr 9.67e-05
[train]   185/1243  loss 0.2246  lr 9.64e-05
[train]   190/1243  loss 0.2499  lr 9.62e-05
[train]   195/1243  loss 0.2309  lr 9.59e-05
[train]   200/1243  loss 0.2403  lr 9.57e-05
[train]   205/1243  loss 0.2394  lr 9.54e-05
[train]   210/1243  loss 0.2490  lr 9.51e-05
[train]   215/1243  loss 0.2195  lr 9.48e-05
[train]   220/1243  loss 0.2957  lr 9.45e-05
[train]   225/1243  loss 0.2300  lr 9.42e-05
[train]   230/1243  loss 0.3132  lr 9.39e-05
[train]   235/1243  loss 0.2337  lr 9.36e-05
[train]   240/1243  loss 0.2564  lr 9.33e-05
[train]   245/1243  loss 0.2798  lr 9.30e-05
[train]   250/1243  loss 0.3074  lr 9.26e-05
[train]   255/1243  loss 0.2500  lr 9.23e-05
[train]   260/1243  loss 0.2802  lr 9.19e-05
[train]   265/1243  loss 0.2921  lr 9.16e-05
[train]   270/1243  loss 0.2200  lr 9.12e-05
[train]   275/1243  loss 0.2956  lr 9.08e-05
[train]   280/1243  loss 0.2306  lr 9.05e-05
[train]   285/1243  loss 0.2652  lr 9.01e-05
[train]   290/1243  loss 0.2381  lr 8.97e-05
[train]   295/1243  loss 0.1744  lr 8.93e-05
[train]   300/1243  loss 0.2423  lr 8.89e-05
[train]   305/1243  loss 0.3202  lr 8.85e-05
[train]   310/1243  loss 0.2285  lr 8.80e-05
[train]   315/1243  loss 0.2523  lr 8.76e-05
[train]   320/1243  loss 0.2460  lr 8.72e-05
[train]   325/1243  loss 0.2608  lr 8.67e-05
[train]   330/1243  loss 0.2719  lr 8.63e-05
[train]   335/1243  loss 0.2892  lr 8.58e-05
[train]   340/1243  loss 0.1804  lr 8.54e-05
[train]   345/1243  loss 0.2390  lr 8.49e-05
[train]   350/1243  loss 0.2009  lr 8.44e-05
[train]   355/1243  loss 0.2736  lr 8.40e-05
[train]   360/1243  loss 0.2522  lr 8.35e-05
[train]   365/1243  loss 0.2207  lr 8.30e-05
[train]   370/1243  loss 0.2210  lr 8.25e-05
[train]   375/1243  loss 0.2222  lr 8.20e-05
[train]   380/1243  loss 0.3130  lr 8.15e-05
[train]   385/1243  loss 0.2196  lr 8.10e-05
[train]   390/1243  loss 0.2153  lr 8.05e-05
[train]   395/1243  loss 0.2733  lr 8.00e-05
[train]   400/1243  loss 0.1729  lr 7.94e-05
[ val ]   400/1243  loss 0.3572  (191s)
[train]   405/1243  loss 0.2092  lr 7.89e-05
[train]   410/1243  loss 0.2644  lr 7.84e-05
[train]   415/1243  loss 0.2733  lr 7.78e-05
[train]   420/1243  loss 0.2346  lr 7.73e-05
[train]   425/1243  loss 0.3378  lr 7.67e-05
[train]   430/1243  loss 0.2116  lr 7.62e-05
[train]   435/1243  loss 0.2448  lr 7.56e-05
[train]   440/1243  loss 0.2811  lr 7.51e-05
[train]   445/1243  loss 0.2311  lr 7.45e-05
[train]   450/1243  loss 0.1833  lr 7.39e-05
[train]   455/1243  loss 0.2368  lr 7.34e-05
[train]   460/1243  loss 0.2726  lr 7.28e-05
[train]   465/1243  loss 0.2200  lr 7.22e-05
[train]   470/1243  loss 0.2201  lr 7.16e-05
[train]   475/1243  loss 0.1878  lr 7.10e-05
[train]   480/1243  loss 0.2050  lr 7.04e-05
[train]   485/1243  loss 0.2699  lr 6.98e-05
[train]   490/1243  loss 0.2280  lr 6.92e-05
[train]   495/1243  loss 0.2979  lr 6.86e-05
[train]   500/1243  loss 0.3028  lr 6.80e-05
[train]   505/1243  loss 0.2181  lr 6.74e-05
[train]   510/1243  loss 0.2382  lr 6.68e-05
[train]   515/1243  loss 0.2283  lr 6.62e-05
[train]   520/1243  loss 0.2748  lr 6.56e-05
[train]   525/1243  loss 0.3216  lr 6.50e-05
[train]   530/1243  loss 0.2523  lr 6.43e-05
[train]   535/1243  loss 0.2191  lr 6.37e-05
[train]   540/1243  loss 0.2203  lr 6.31e-05
[train]   545/1243  loss 0.2395  lr 6.24e-05
[train]   550/1243  loss 0.2405  lr 6.18e-05
[train]   555/1243  loss 0.2182  lr 6.12e-05
[train]   560/1243  loss 0.1544  lr 6.05e-05
[train]   565/1243  loss 0.2066  lr 5.99e-05
[train]   570/1243  loss 0.2037  lr 5.93e-05
[train]   575/1243  loss 0.2739  lr 5.86e-05
[train]   580/1243  loss 0.2290  lr 5.80e-05
[train]   585/1243  loss 0.2264  lr 5.73e-05
[train]   590/1243  loss 0.1910  lr 5.67e-05
[train]   595/1243  loss 0.3203  lr 5.60e-05
[train]   600/1243  loss 0.1992  lr 5.54e-05
[train]   605/1243  loss 0.2539  lr 5.48e-05
[train]   610/1243  loss 0.2354  lr 5.41e-05
[train]   615/1243  loss 0.1882  lr 5.35e-05
[train]   620/1243  loss 0.2779  lr 5.28e-05
[train]   625/1243  loss 0.2388  lr 5.22e-05
[train]   630/1243  loss 0.2140  lr 5.15e-05
[train]   635/1243  loss 0.2071  lr 5.08e-05
[train]   640/1243  loss 0.2627  lr 5.02e-05
[train]   645/1243  loss 0.2118  lr 4.95e-05
[train]   650/1243  loss 0.1622  lr 4.89e-05
[train]   655/1243  loss 0.2318  lr 4.82e-05
[train]   660/1243  loss 0.2621  lr 4.76e-05
[train]   665/1243  loss 0.2512  lr 4.69e-05
[train]   670/1243  loss 0.2663  lr 4.63e-05
[train]   675/1243  loss 0.2308  lr 4.56e-05
[train]   680/1243  loss 0.2087  lr 4.50e-05
[train]   685/1243  loss 0.2274  lr 4.43e-05
[train]   690/1243  loss 0.2353  lr 4.37e-05
[train]   695/1243  loss 0.2438  lr 4.30e-05
[train]   700/1243  loss 0.2344  lr 4.24e-05
[train]   705/1243  loss 0.1694  lr 4.18e-05
[train]   710/1243  loss 0.1702  lr 4.11e-05
[train]   715/1243  loss 0.2676  lr 4.05e-05
[train]   720/1243  loss 0.1551  lr 3.98e-05
[train]   725/1243  loss 0.2391  lr 3.92e-05
[train]   730/1243  loss 0.2666  lr 3.86e-05
[train]   735/1243  loss 0.2576  lr 3.79e-05
[train]   740/1243  loss 0.1796  lr 3.73e-05
[train]   745/1243  loss 0.2623  lr 3.67e-05
[train]   750/1243  loss 0.3019  lr 3.60e-05
[train]   755/1243  loss 0.2374  lr 3.54e-05
[train]   760/1243  loss 0.2807  lr 3.48e-05
[train]   765/1243  loss 0.1956  lr 3.42e-05
[train]   770/1243  loss 0.2317  lr 3.36e-05
[train]   775/1243  loss 0.2127  lr 3.29e-05
[train]   780/1243  loss 0.2110  lr 3.23e-05
[train]   785/1243  loss 0.2759  lr 3.17e-05
[train]   790/1243  loss 0.1757  lr 3.11e-05
[train]   795/1243  loss 0.2439  lr 3.05e-05
[train]   800/1243  loss 0.2224  lr 2.99e-05
[ val ]   800/1243  loss 0.3350  (186s)
[train]   805/1243  loss 0.1972  lr 2.93e-05
[train]   810/1243  loss 0.2322  lr 2.87e-05
[train]   815/1243  loss 0.2038  lr 2.81e-05
[train]   820/1243  loss 0.2678  lr 2.76e-05
[train]   825/1243  loss 0.2076  lr 2.70e-05
[train]   830/1243  loss 0.2544  lr 2.64e-05
[train]   835/1243  loss 0.2204  lr 2.58e-05
[train]   840/1243  loss 0.2264  lr 2.53e-05
[train]   845/1243  loss 0.2464  lr 2.47e-05
[train]   850/1243  loss 0.2051  lr 2.41e-05
[train]   855/1243  loss 0.1567  lr 2.36e-05
[train]   860/1243  loss 0.1928  lr 2.30e-05
[train]   865/1243  loss 0.2207  lr 2.25e-05
[train]   870/1243  loss 0.1735  lr 2.19e-05
[train]   875/1243  loss 0.1715  lr 2.14e-05
[train]   880/1243  loss 0.2403  lr 2.09e-05
[train]   885/1243  loss 0.2498  lr 2.03e-05
[train]   890/1243  loss 0.2598  lr 1.98e-05
[train]   895/1243  loss 0.2066  lr 1.93e-05
[train]   900/1243  loss 0.1982  lr 1.88e-05
[train]   905/1243  loss 0.1867  lr 1.83e-05
[train]   910/1243  loss 0.2416  lr 1.78e-05
[train]   915/1243  loss 0.2619  lr 1.73e-05
[train]   920/1243  loss 0.2813  lr 1.68e-05
[train]   925/1243  loss 0.2295  lr 1.63e-05
[train]   930/1243  loss 0.2319  lr 1.58e-05
[train]   935/1243  loss 0.2602  lr 1.54e-05
[train]   940/1243  loss 0.1439  lr 1.49e-05
[train]   945/1243  loss 0.1525  lr 1.44e-05
[train]   950/1243  loss 0.2922  lr 1.40e-05
[train]   955/1243  loss 0.2326  lr 1.35e-05
[train]   960/1243  loss 0.2458  lr 1.31e-05
[train]   965/1243  loss 0.2143  lr 1.27e-05
[train]   970/1243  loss 0.1785  lr 1.22e-05
[train]   975/1243  loss 0.2239  lr 1.18e-05
[train]   980/1243  loss 0.1898  lr 1.14e-05
[train]   985/1243  loss 0.1852  lr 1.10e-05
[train]   990/1243  loss 0.2265  lr 1.06e-05
[train]   995/1243  loss 0.1972  lr 1.02e-05
[train]  1000/1243  loss 0.2569  lr 9.78e-06
[train]  1005/1243  loss 0.2381  lr 9.40e-06
[train]  1010/1243  loss 0.1932  lr 9.02e-06
[train]  1015/1243  loss 0.2452  lr 8.65e-06
[train]  1020/1243  loss 0.3300  lr 8.29e-06
[train]  1025/1243  loss 0.2208  lr 7.93e-06
[train]  1030/1243  loss 0.2505  lr 7.58e-06
[train]  1035/1243  loss 0.2031  lr 7.24e-06
[train]  1040/1243  loss 0.2186  lr 6.91e-06
[train]  1045/1243  loss 0.2154  lr 6.58e-06
[train]  1050/1243  loss 0.2200  lr 6.26e-06
[train]  1055/1243  loss 0.2300  lr 5.95e-06
[train]  1060/1243  loss 0.2082  lr 5.64e-06
[train]  1065/1243  loss 0.2456  lr 5.35e-06
[train]  1070/1243  loss 0.1976  lr 5.06e-06
[train]  1075/1243  loss 0.1412  lr 4.78e-06
[train]  1080/1243  loss 0.2155  lr 4.50e-06
[train]  1085/1243  loss 0.2204  lr 4.23e-06
[train]  1090/1243  loss 0.2521  lr 3.98e-06
[train]  1095/1243  loss 0.2783  lr 3.73e-06
[train]  1100/1243  loss 0.2060  lr 3.48e-06
[train]  1105/1243  loss 0.1951  lr 3.25e-06
[train]  1110/1243  loss 0.2165  lr 3.02e-06
[train]  1115/1243  loss 0.1810  lr 2.80e-06
[train]  1120/1243  loss 0.2338  lr 2.59e-06
[train]  1125/1243  loss 0.1469  lr 2.39e-06
[train]  1130/1243  loss 0.2131  lr 2.19e-06
[train]  1135/1243  loss 0.2281  lr 2.01e-06
[train]  1140/1243  loss 0.1875  lr 1.83e-06
[train]  1145/1243  loss 0.2247  lr 1.66e-06
[train]  1150/1243  loss 0.2020  lr 1.49e-06
[train]  1155/1243  loss 0.2061  lr 1.34e-06
[train]  1160/1243  loss 0.2658  lr 1.19e-06
[train]  1165/1243  loss 0.1826  lr 1.06e-06
[train]  1170/1243  loss 0.2192  lr 9.28e-07
[train]  1175/1243  loss 0.1685  lr 8.07e-07
[train]  1180/1243  loss 0.1601  lr 6.94e-07
[train]  1185/1243  loss 0.2182  lr 5.90e-07
[train]  1190/1243  loss 0.2164  lr 4.95e-07
[train]  1195/1243  loss 0.2000  lr 4.07e-07
[train]  1200/1243  loss 0.2157  lr 3.29e-07
[ val ]  1200/1243  loss 0.3292  (187s)
[train]  1205/1243  loss 0.2086  lr 2.58e-07
[train]  1210/1243  loss 0.1888  lr 1.96e-07
[train]  1215/1243  loss 0.2497  lr 1.43e-07
[train]  1220/1243  loss 0.1709  lr 9.78e-08
[train]  1225/1243  loss 0.1867  lr 6.13e-08
[train]  1230/1243  loss 0.2775  lr 3.33e-08
[train]  1235/1243  loss 0.2150  lr 1.38e-08
[train]  1240/1243  loss 0.2360  lr 2.72e-09
[ val ]  1243/1243  loss 0.3289  (189s)
peak VRAM GB: 7.09
adapter saved -> checkpoints/vi_lora

## 7 · Evaluate the fine-tuned model on the test split

In [9]:
from vi_norm import normalize_vi, wer_cer   # shared with 01_eval_baseline.ipynb

model.config.use_cache = True
model.eval()
processor.tokenizer.padding_side = "left"   # required for correct batched generation
BATCH_SIZE = 8   # lower to 4 if you hit CUDA OOM

@torch.no_grad()
def transcribe_batch(rows, batch_size=BATCH_SIZE, max_new_tokens=440):
    from tqdm.auto import tqdm
    rows = list(rows)
    order = sorted(range(len(rows)), key=lambda i: rows[i]["duration"])
    hyps = [None] * len(rows)
    for s in tqdm(range(0, len(order), batch_size), desc="eval (batched)"):
        chunk = order[s:s + batch_size]
        arrs = [data_prep.read_audio(rows[i]["audio_path"])[0] for i in chunk]
        inputs = processor.apply_transcription_request(
            audio=arrs, language="Vietnamese").to(model.device, model.dtype)
        out = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False)
        gen = out[:, inputs["input_ids"].shape[1]:]
        for i, txt in zip(chunk, processor.decode(gen, return_format="transcription_only")):
            hyps[i] = txt
    return hyps

In [10]:
import pathlib
import pandas as pd

pathlib.Path("results").mkdir(exist_ok=True)   # first write of the notebook

test_rows = list(test)
hyps = transcribe_batch(test_rows)   # batched, ~3x faster
rows = [{"audio_file": os.path.basename(r["audio_path"]), "audio_path": r["audio_path"],
         "channel": r["channel"], "bucket": r["bucket"], "duration": round(r["duration"], 2),
         "ref": r["text"], "hyp": h}
        for r, h in zip(test_rows, hyps)]
df = pd.DataFrame(rows)
df.to_csv("results/lora_predictions.csv", index=False)
lora_overall = wer_cer(df["ref"], df["hyp"])
lora_by = {b: wer_cer(g["ref"], g["hyp"]) for b, g in df.groupby("bucket")}
print("LoRA OVERALL:", lora_overall)
for b, m in lora_by.items():
    print(f"  {b}: WER={m['wer']:.3f} CER={m['cer']:.3f} (n={m['n']})")

eval (batched):   0%|          | 0/15 [00:00<?, ?it/s]

LoRA OVERALL: {'wer': 0.06026587887740029, 'cer': 0.02838768948093707, 'n': 114, 'wer_legacy': 0.06475690942102078, 'cer_legacy': 0.03039693428584946}
  30-60: WER=0.059 CER=0.028 (n=20)
  5-30: WER=0.061 CER=0.029 (n=94)

## 8 · Before / after comparison

In [11]:
import json, pathlib
pathlib.Path("results").mkdir(exist_ok=True)
with open("results/lora_metrics.json", "w", encoding="utf-8") as f:
    json.dump({"overall": lora_overall, "by_bucket": lora_by}, f, ensure_ascii=False, indent=2)

try:
    baseline = json.load(open("results/baseline_metrics.json"))
    comp = pd.DataFrame({
        "metric": ["WER", "CER"],
        "baseline": [baseline["overall"]["wer"], baseline["overall"]["cer"]],
        "lora": [lora_overall["wer"], lora_overall["cer"]],
    })
    comp["abs_delta"] = comp["lora"] - comp["baseline"]
    comp["rel_%"] = 100 * comp["abs_delta"] / comp["baseline"]
    print(comp.to_string(index=False))
except FileNotFoundError:
    print("Run 01_eval_baseline.ipynb first to get baseline_metrics.json for the comparison.")
    comp = None
comp

metric  baseline     lora  abs_delta     rel_%
   WER  0.059577 0.060266   0.000689  1.157025
   CER  0.030340 0.028388  -0.001952 -6.434519

  metric  baseline      lora  abs_delta     rel_%
0    WER  0.059577  0.060266   0.000689  1.157025
1    CER  0.030340  0.028388  -0.001952 -6.434519

## 9 · External benchmarks — before / after

Scores the fine-tuned adapter on the same benchmark suite as notebook 1 and
diffs it against `results/bench_metrics.json`.

> **These are no longer zero-shot.** The mixture trains on the *train* splits of
> VIVOS and Common Voice, and on 90% of the VLSP corpus (by transcript hash), so
> all three test sets are now **in-domain**. The improvement here measures
> adaptation to these datasets, not general Vietnamese ASR gains. The genuinely
> held-out, speaker-disjoint number is the viVoice `test` result in section 7.
>
> The eval rows themselves stay clean: VIVOS/Common Voice test splits are
> untouched, and the VLSP slice is hash-disjoint from everything trained on.

If the baseline file was produced before the VLSP held-out slice existed, the
cell below says so — re-run notebook 1 section 8 to refresh it.

In [12]:
import bench

processor.tokenizer.padding_side = "left"
lora_bench, lora_bench_frames = bench.run_benchmarks(
    model, processor, ["vivos", "cmv_vi", "vlsp2020_100h"],
    token=os.environ.get("HF_TOKEN"), batch_size=8,
)

pathlib.Path("results").mkdir(exist_ok=True)
for name, f in lora_bench_frames.items():
    f.to_csv(f"results/lora_bench_{name}_predictions.csv", index=False)
with open("results/lora_bench_metrics.json", "w", encoding="utf-8") as f:
    json.dump(lora_bench, f, ensure_ascii=False, indent=2)
print("saved -> results/lora_bench_metrics.json")

=== vivos · htdung167/vivos-preprocessed-v2 [test] ===
    Official VIVOS test split, 760 utterances.

loading vivos: 0it [00:00, ?it/s]

transcribing (batched):   0%|          | 0/95 [00:00<?, ?it/s]

   WER=0.0603  CER=0.0278  (legacy WER=0.0603)  n=760

=== cmv_vi · fixie-ai/common_voice_17_0 [test] ===
    Common Voice 17.0 Vietnamese test split, 1274 utterances.

loading cmv_vi: 0it [00:00, ?it/s]

transcribing (batched):   0%|          | 0/160 [00:00<?, ?it/s]

   WER=0.0987  CER=0.0449  (legacy WER=0.0990)  n=1274

=== vlsp2020_100h · data/vi_mix/heldout_vlsp2020_100h [test] ===
    VLSP 2020 VinBigData 100h corpus, 5% held-out slice assigned by transcript hash. Own benchmark, not PhoWhisper's T1/T2. ~96% transcript accuracy -> read the delta, not the absolute.

loading vlsp2020_100h: 0it [00:00, ?it/s]

transcribing (batched):   0%|          | 0/35 [00:00<?, ?it/s]

   WER=0.0957  CER=0.0518  (legacy WER=0.0960)  n=276
saved -> results/lora_bench_metrics.json

In [13]:
try:
    base_bench = json.load(open("results/bench_metrics.json"))
except FileNotFoundError:
    base_bench = {}
    print("No results/bench_metrics.json — run notebook 1 section 8 for the baseline.")

rows = []
for name, l in lora_bench.items():
    b = base_bench.get(name)
    if b and b.get("source") != l.get("source"):
        print(f"WARNING {name}: baseline came from {b.get('source')!r} but this run "
              f"used {l.get('source')!r}. Re-run notebook 1 section 8 — the "
              f"comparison below is not valid for this row.")
    rows.append({
        "dataset": name,
        "n": l["n"],
        "baseline WER %": round(100 * b["wer"], 2) if b else None,
        "LoRA WER %": round(100 * l["wer"], 2),
        "abs delta": round(100 * (l["wer"] - b["wer"]), 2) if b else None,
        "rel %": round(100 * (l["wer"] - b["wer"]) / b["wer"], 1) if b else None,
        "zero-shot?": "no — trained on this dataset",
    })
bench_cmp = pd.DataFrame(rows)
print()
print(bench_cmp.to_string(index=False))
bench_cmp

      dataset    n  baseline WER %  LoRA WER %  abs delta  rel %                   zero-shot?
        vivos  760            7.19        6.03      -1.15  -16.0 no — trained on this dataset
       cmv_vi 1274           11.18        9.87      -1.31  -11.7 no — trained on this dataset
vlsp2020_100h  276           13.16        9.57      -3.59  -27.3 no — trained on this dataset

,dataset,n,baseline WER %,LoRA WER %,abs delta,rel %,zero-shot?
0,vivos,760,7.19,6.03,-1.15,-16.0,no — trained on this dataset
1,cmv_vi,1274,11.18,9.87,-1.31,-11.7,no — trained on this dataset
2,vlsp2020_100h,276,13.16,9.57,-3.59,-27.3,no — trained on this dataset